name: Publish npm package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i --ignore-scripts
      - run: npm ci --ignore-scripts
      - name: Run tests
        run: npm run test --ignore-scripts
      - name: Build
        run: npm run build --ignore-scripts
      - name: Copy required files
        run: npm run copy --ignore-scripts

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i --ignore-scripts
      - run: npm ci --ignore-scripts
      - run: npm run build --ignore-scripts
      - run: npm publish ./dist --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
